import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { AuthProvider } from "./_components/AuthProvider";
import { StaffAuthProvider } from "@/context/StaffContext";
import { CrudProvider } from "@/context/SSR-inventoryContext";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//webpage -> relative to the viewport/device width; container/elements -> relative to the body; fonts-> relative to the container
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AuthProvider>
          <div className="w-screen flex flex-col items-center">
            <div className="max-w-560 flex flex-col ">{children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
