import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSideBar } from "./_components/AppSideBar";
import BaseStructure from "./_components/BaseStructure";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "./_components/AuthProvider";
import { CrudProvider } from "./staff_nomnom/dishesManagement/SSR-inventoryContext";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//webpage -> relative to the viewport/device width; container/elements -> relative to the body; fonts-> relative to the container
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AuthProvider>
          <CrudProvider>
            <CartProvider>{children}</CartProvider>
          </CrudProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
